### ISSUE TITLE
[Performance] Painting on mousemove

### ISSUE THREAD

**Issue by motss** [Redbility/paper-carousel#10]
The elements paints on every mousemove and it hurts performance on low end devices.

**Comment by DavidTorrijos** [comment]
Hi @motss,
the mousemove event we are not call it at any moment, therefore, this event can not hurts performance.
Probably you're talking about of resize or swipe events.
The resize event is just executed when you are resizing the window.
Finally, if the performance problem has been generated by swipe event, we just can tell you that this event is a functionality that we wanna keep.

If you are talking about of other event, please, bring us more information for review it.
Thank you!

**Comment by DavidTorrijos** [comment]
Hi @motss 
after 2 weeks without responds, we understand that you are found other way to resolve this issue.
If this problem is not resolved, please, open another issue.

Thank you!
