### ISSUE TITLE
Info - Compiled CSS

### ISSUE THREAD

**Issue by equinusocio** [Redbility/paper-carousel#12]
Hi, how do you inject compiled css inside the html? I'm try to achieve the same result but i don't like to much the injection (like gulp-inject)

**Comment by DavidTorrijos** [comment]
Hi @equinusocio, 
We don't inject css compiled directly to the html.
The way that we have to add css inside the html is the next one:
We have a .PUG file where we make a include from a .CSS file that has been compiled by Gulp from a .SCSS file.

In the "Source" folder you can see the .PUG, .SCSS and .COFFEE files that we use to create the component.

Thank you!

**Comment by equinusocio** [comment]
Thank you man.
