### ISSUE TITLE
Make carousel loop

### ISSUE THREAD

**Issue by ipwa** [Redbility/paper-carousel#27]
I don't see this on the options, it would be great to make the carousel continue to the first slide after the last.

**Comment by oscarsolas** [comment]
Hi @ipwa,
Thaks for your report.
We will consider it for future improvements.

**Comment by heyMP** [comment]
I can help with this, I'm adding it to a local component now.  @oscarsolas would you be able to un-minify the development branch so I can add my code and send you a pull request?

**Comment by oscarsolas** [comment]
I have included "tools" folder in "develop" branch, this folder contains package.json and gulpFile.js to compile the source files (pug, sass and coffee).
You can run "gulp serve" task to compile it.

I hope it can be useful to you.
Thanks.

**Comment by DavidTorrijos** [comment]
Hi @ipwa and @heyMP ,
We just update the component, you can found the new loop functionality at the last release.
Thank you.
