### ISSUE TITLE
Captions

### ISSUE THREAD

**Issue by phidias51** [Redbility/paper-carousel#28]
I was wondering if you had thought about supporting captions with the paper carousel? Or is there another way of doing it?

```
<paper-carousel items="1" dotText="false">
    <figure>
      <img src="https://unsplash.it/800/500/?image=257" draggable="false"/>
      <figcaption>Canal</figcaption>
    </figure>
    <figure>
    <img src="https://unsplash.it/800/500/?image=250" draggable="false"/>
      <figcaption>Camera</figcaption>
  </figure>
</paper-carousel>
```

**Comment by DavidTorrijos** [comment]
Hi @phidias51 ,
currently we have not contemplate the captions, but the way you propose to do it looks properly. You will just need apply styles to the captions.
Thanks for the suggestion!
