### ISSUE TITLE
doesn't work with dom-repeat as data

### ISSUE THREAD

**Issue by ryanwtyler** [Redbility/paper-carousel#7]
<paper-carousel items="4" responsive="600:2, 460:1" controls="true">
          <template is="dom-repeat" items="{{data}}">

            <div >[[item]]</div>

          </template>
        </paper-carousel>

gives an error : `Cannot read property 'children' of null`

**Comment by oscarsolas** [comment]
Hello @ryanwtyler, thank you for your report.

I have been testing with dom-repeat and I have not been able to reproduce it.
Instead I have been able to reproduce another error related to the item count and that I already fixed it.

Could you give me more information? Version of the component? Polymer version? Version of the browser?

Thank you!

**Comment by DavidTorrijos** [comment]
Hi @ryanwtyler,
after 2 weeks without responds, we understand that you are found other way to resolve this issue.
If this problem is not resolved, please, open another issue.

Thank you!
