### ISSUE TITLE
Nested Component Issue

### ISSUE THREAD

**Issue by mukeshyadav** [Redbility/paper-carousel#9]
Not working if using in nested component, like i have developed one more component and used there its giving error.

**Comment by DavidTorrijos** [comment]
Hi @mukeshyadav ,
could you give us the log error and the code that you are writing?
Also, would be great if you could give us more information like: Component version, Polymer version, browser version...

Thanks!

**Comment by DavidTorrijos** [comment]
Hi @mukeshyadav,
after 2 weeks without responds, we understand that you are found other way to resolve this issue.
If this problem is not resolved, please, open another issue.

Thank you!
